config/routes.rb
Rails.application.routes.draw do
  resources :looks
  get 'recipes/index'
  root 'recipes#index'

end

app/models/look.rb
class Look < ApplicationRecord
end

app/models/recipe.rb
class Recipe
    include HTTParty
        
    base_uri 'http://www.recipepuppy.com/api'
    default_params onlyImages: 1

    format :json

    def self.for ( keyword  )
        get('', query: { q: keyword })['results']
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loo_ks_controller.rb
class LooKsController < ApplicationController
  before_action :set_look, only: [:show, :edit, :update, :destroy]

  # GET /looks
  # GET /looks.json
  def index
    @looks = Look.all
  end

  # GET /looks/1
  # GET /looks/1.json
  def show
  end

  # GET /looks/new
  def new
    @look = Look.new
  end

  # GET /looks/1/edit
  def edit
  end

  # POST /looks
  # POST /looks.json
  def create
    @look = Look.new(look_params)

    respond_to do |format|
      if @look.save
        format.html { redirect_to @look, notice: 'Look was successfully created.' }
        format.json { render :show, status: :created, location: @look }
      else
        format.html { render :new }
        format.json { render json: @look.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /looks/1
  # PATCH/PUT /looks/1.json
  def update
    respond_to do |format|
      if @look.update(look_params)
        format.html { redirect_to @look, notice: 'Look was successfully updated.' }
        format.json { render :show, status: :ok, location: @look }
      else
        format.html { render :edit }
        format.json { render json: @look.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /looks/1
  # DELETE /looks/1.json
  def destroy
    @look.destroy
    respond_to do |format|
      format.html { redirect_to looks_url, notice: 'Look was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_look
      @look = Look.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def look_params
      params.require(:look).permit(:Name, :Ingredients, :Loves)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @search = params[:search] || 'chocolate'
    @recipes= Recipe.for(@search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loo_ks_helper.rb
module LooKsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipePuppyBootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loo_ks/_form.html.erb
<%= form_with(model: look, local: true) do |form| %>
  <% if look.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(look.errors.count, "error") %> prohibited this look from being saved:</h2>

      <ul>
        <% look.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Ingredients %>
    <%= form.text_field :Ingredients %>
  </div>

  <div class="field">
    <%= form.label :Loves %>
    <%= form.number_field :Loves %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loo_ks/edit.html.erb
<h1>Editing Look</h1>

<%= render 'form', look: @look %>

<%= link_to 'Show', @look %> |
<%= link_to 'Back', looks_path %>

app/views/loo_ks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Looks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
      <th>Loves</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @looks.each do |look| %>
      <tr>
        <td><%= look.Name %></td>
        <td><%= look.Ingredients %></td>
        <td><%= look.Loves %></td>
        <td><%= link_to 'Show', look %></td>
        <td><%= link_to 'Edit', edit_look_path(look) %></td>
        <td><%= link_to 'Destroy', look, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Look', new_look_path %>

app/views/loo_ks/new.html.erb
<h1>New Look</h1>

<%= render 'form', look: @look %>

<%= link_to 'Back', looks_path %>

app/views/loo_ks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @look.Name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @look.Ingredients %>
</p>

<p>
  <strong>Loves:</strong>
  <%= @look.Loves %>
</p>

<%= link_to 'Edit', edit_look_path(@look) %> |
<%= link_to 'Back', looks_path %>

app/views/recipes/index.html.erb
<h1> Recipes for <%=@search%> </h1>
<h3> If you wana look for some other dish then do me a favour, in the search bar just add /?search=yourdishname :') I'll solve the issue asap! </h3>
<table border ="1">
    <tr>
        <th> Photo</th>
        <th> Title </th>
        <th> Ingredients </th>
        
    </tr>
    <% if @recipes.nil? %>
	    <h3>I am sorry. I didnt find any recipe! Kya bana rhe ho esa guru???</h3>
    <% else %>
        <% @recipes.each do |recipe| %>  
        <tr>
                <td> <%= link_to image_tag(recipe["thumbnail"]), recipe["href"] %> </a> </td>
                <td> <%= link_to sanitize(recipe["title"]), recipe["href"] %> </td>
                <td> <%= recipe["ingredients"] %> </td>
        </tr>
        <% end %>
    <% end %>
</table>